ir_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0050000000000000001
  kinematics_solver_timeout: 0.0050000000000000001

ir_gripper:
  kinematics_solver: moveit_simple_kinematics/SimpleKinematics
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05